# Grid World RL

In [66]:
import numpy as np


class Grid_World():
    def __init__(self, size, start = (0,0), walls = None, traps = None, intermediate_goals = None, goals = None):
        
        self.A = [(1,0), (0,1), (-1,0), (0,-1)]
        
        self.gameover, self.win, self.lose = ( False, False, False )
        
        self.rows = size[0]
        self.cols = size[1]
        
        self.player_pos = start #np.array(start)
        
        self.traps = traps
        self.goals = goals
        
        # board:
        # 0 is empty
        # -1 is wall
        # -10 is trap
        # +1 is intermediate_goal
        # +10 is goal
        # #2 is player
        
        self.board = np.zeros((self.rows, self.cols))
        
        #self.board[start] = 2
        
        for wall in walls:
            self.board[wall] = -1
            
        for trap in traps:
            self.board[trap] = -10
            
        for intermediate_goal in intermediate_goals:
            self.board[intermediate_goal] = 1
            
        for goal in goals:
            self.board[goal] = 10
        
    def get_board(self):
        return self.board
    
    def pass_action(self, action):
        print(action)
        self.player_pos = ( self.player_pos[0] + action[0], self.player_pos[1] + action[1] ) #self.player_pos += action
        return self.player_pos
    
    def get_action(self):
        return self.A[np.random.choice([x for x, _ in enumerate(self.A)])]# optimize!!!
    
    def check_gameover(self):
        if self.player_pos in self.traps:
            self.gameover = True
            self.win = True
        if self.player_pos in self.goals:
            self.gameover = True
            self.lose = True
        return (self.gameover, self.win, self.lose)
        
    
    

In [67]:
grid_world = Grid_World( (3,3), start = (0,1), walls = [(1,1)], traps = [(0,2)], intermediate_goals = [], goals = [(2,2)] )
grid_world.get_board()

i = 0

while(i < 100):
    
    grid_world.pass_action(grid_world.get_action())
    
    gameover, win, lose = grid_world.check_gameover()
    
    if gameover == True:
        if win == True:
            print('win')
        else:
            print('lose')
        print(grid_world.get_board())
        break
    
    i += 1

(1, 0)
(1, 0)
(0, 1)
lose
[[  0.   0. -10.]
 [  0.  -1.   0.]
 [  0.   0.  10.]]


In [20]:
arr = np.array((1,2))
arr + (0,1)

array([1, 3])

In [32]:
np.random.choice([x for x, _ in enumerate([(1,0),(0,1)])])

0

In [33]:
gameover, win, lose = (False, False, False)
print(gameover, win, lose )

False False False


In [60]:
np.array([(1,2), (4,3)]) == (1,2)

array([[ True,  True],
       [False, False]])

In [71]:
(1,2) in list(np.array([(1,2),(3,4)]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()